# Generated by Django 3.2.16 on 2024-03-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20240225_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog.post_images', verbose_name='Изображение к публикации'),
        ),
    ]
